---
title: "notes"
author: "Nate Lant"
date: "1/14/2020"
output: html_document
---

Just looking at the introductions...

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TNC's and Disabled Access (SF)
Since establishing oversight of TNCs in 2013, the California Public Utilities Commission (CPUC) has 
promulgated only a few regulations and minimal oversight to ensure equal access for passengers with 
disabilities. New legislation, effective January 1, 2019, known as Senate Bill 1376: The TNC Access for 
All Act (Hill), provides the CPUC with the mandate to improve access to TNC service for wheelchair users 
and others with disabilities, as well as the opportunity to work with stakeholders to build public trust 
and increase transparency.

San Francisco is not the only large, urban city addressing accessibility of TNCs. A review of Boston, 
Chicago, and New York City found that peer cities are grappling with similar challenges and opportunities 
to improve access to TNCs for persons with disabilities.

Riders with disabilities, like the general public, want to have choices. For example, bus service may 
work well for a disabled person’s trips to work and school, but they may want to use a taxi or TNC on an 
evening after a movie. Riders also want to choose whether to pay less by sharing a ride or to spend more 
to go directly to their destination.

The arrival of emerging mobility services has expanded transportation options for some but it has not 
expanded options equally for all. For approximately 90,000 San Francisco residents with disabilities 
(almost 11% of the population) TNCs may not be an option either some or all the time. While people with 
disabilities are more reliant on for-hire services and make twice the number of for-hire trips than non-
disabled persons per year, they are more reliant on taxicabs. People with disabilities report taking 
twice as many taxi trips as TNC trips [@Schaller2018] while overall there are approximately 12 times as 
many TNC trips as taxi trips during a typical weekday in San Francisco (San Francisco County Transportation 
Authority, June 2017).

The rapid expansion of TNC services has also degraded the quality and availability of on-demand 
transportation access for riders who require a wheelchair accessible vehicle by upending the existing 
taxi industry. The subsequent reduction in accessible ramp taxis has compromised the availability of 
accessible taxis under the San Francisco Paratransit Taxi and Paratransit Plus programs 
[@Consulting2018].


## NY State TNC Accessibility Task Force
There is a legislative history (if I find that relevant)

In general, the cost of para-transit is high for many communities. For instance, “The average cost of operating a single paratransit trip is about \$23 in the U.S., compared with less than \$4 for the average trip on bus or light rail. In Boston, the average cost per ride is about \$45, in Washington, about \$50, and in New York, nearly \$57. Transit agencies nationwide logged about 223 million paratransit trips at a cost exceeding \$5.1 billion — about 12 percent of total transit operating costs — in 2013, according to the most recent data from the American Public Transportation Association. (https://www.sandiegouniontribune.com/sdut-transit-systems-eye-uber-lyft-for-savings-on-the-2016apr10-story.html).

<!--- this is my summary from the prospectus, not an actual quote from the document --->
In 2018, the Taxi and Limousine Commission (TLC) in New York City issued a mandate requiring Uber, Lyft 
and Via to make wheelchair accessible service a growing part of their operations. While this particular 
mandate was not adopted, a settlement was reached in the New York State Supreme Court. The NYC TLC 
retained the mandate that would require TNCs to meet a wait-time requirement. The wait time requirement 
states that, by 2021, TNCs must either service at least 80 percent of requests for wheelchair-accessible 
vehicles in under 10 minutes and 90 percent in under 15 minutes, or associate with a company that has 
the capacity to meet those requirements [@Report2019].

#### Cases mentioned
<!--- sources are cited in the document--->
Perhaps more significantly, the Massachusetts Bay Transportation Authority, serving the greater Boston area, instituted a policy whereby individuals with disabilities can have their rides subsidized with riders only paying the first \$2, and MBTA covering the next \$13.35 This is not only a significant benefit for riders with disabilities, it is also a benefit to MBTA. Boston’s door-to-door service for riders with disabilities and elderly (the Ride) has an annual budget of over \$100 million a year.36 Under “The Ride” program each ride costs \$31, but with the partnership with Uber and Lyft, these rides will cost the agency \$13 – a 70% savings.

In Washington D.C., Metro launched the Abilities Ride program in partnership with Uber and Lyft.37 In this program, the individual pays the first \$5, Metro pays the next \$15, and then the individual is responsible for any amount over \$20.38 This allows riders to take up to 4 rides per day, get same day services, and be accompanied by one personal care assistant at no extra cost.39 However, WMATA was criticized: “The rideshare option is expected to be popular among customers who don’t need wheelchair-accessible vehicles to travel; Still, some people with disabilities and advocates have been critical of Metro’s intent to partner with the companies, saying they lack wheelchair-accessible vehicles and training in dealing with special- needs populations.”40

In other communities, like Chicago, the presence of UberWAV (Wheelchair Accessible Vehicles) appears to be expanding the accessibility of TNCs to individuals who utilize a wheelchair. In fact, the Chicago Tribune reported in late 2017 that Uber had “65 wheelchair-accessible vehicles on the road available through the app.”41 There was clearly more work to be done, and Uber’s Chicago General Manager acknowledges that, “developing and implementing new solutions to the mobility challenge faced by the disability community is an issue we take very seriously.”42


## Travel Patterns of American Adults with Disabilities


## Intelligent Paratransit

## Impacts of limited acces (Bascom and Christensen)

## Strategic Plan 2019-2022

## Policies and Practices for  Meeting ADA Paratransit Demand

## Schaller: New Automobility
People with disabilities are more reliant on for-hire services, in particular taxicabs, than non-disabled persons. While nondisabled people make 4.1 for-hire trips annually, people with disabilities make twice as many trips (8.2 per year). (National data only; sample size too small for geographic detail.) People with disabilities are also more reliant on taxicabs than the general population. People with disabilities take 5.9 taxi trips annually, twice their use of TNCs (2.3 trips per year). 

There is a long history of taxicabs participating in Dial-A-Ride
programs for seniors and persons with disabilities who lack
access to a personal car or the financial means to pay for a taxi.
Public subsidies are needed for patrons to obtain medical care,
go shopping, socialize at senior centers, attend religious services
and so forth.

#### Case Studies
Laguna Beach, for example, contracted with Uber to supplement transportation for senior and disabled passengers following curtailments of local bus service. 

The Pinellas Suncoast Transit Authority in the Tampa and St. Petersburg, Florida area, conducted a two-year pilot with Uber, a cab company and a wheelchair van provider for on-demand trips at night to or from work to participants in an agency program for transportation-disadvantaged persons. 

After an initial microtransit pilot involving the now-defunct company Bridj, the Kansas City Area Transportation Authority is using taxis in its RideKC Freedom program, serving older adults and persons with disabilities with same-day service scheduled through a mobile app or by telephoning a call center. 

Via is developing with the city of Berlin, Germany a van service that complements existing transit service, focusing on late night and weekend travel.

TNCs have recently started to participate in programs that supplement ADA paratransit. A prime example is the pilot by the Boston area transit agency (MBTA) that involves Uber, Lyft and other companies. ADA paratransit users are offered the option of using one of these three companies instead of the regular ADA service. They can make same-day reservations instead of having to call a day or more in advance. Riders pay the same \$2 fare and any amount over \$15 (making for a subsidy of up to \$13 per trip). Lyft provides a call center under its Lyft Concierge program, while Uber addressed smartphone issues by giving away smartphones to some users. 

Another example is the transit agency in Las Vegas, Nevada, which began a pilot earlier this year with Lyft to provide ondemand paratransit service.


## Use of Taxis in Public Transportation for People with Disabilities and Older Adults (2016)

