---
title: "Test Wheelchair Employment and Tours"
author: "Nate Lant"
date: "2/7/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## FUNCTION READ IN FROM 03_methodology.rmd

# read in the trips file
trips_edited <- read_rds("data/nhts_data.rds")
persons_edited <- read_rds("data/persons.rds")
```

## Test for Tours, and tour classification

```{r test.tour, include=F}
# filter people that are in regular sized cities
tours <- read_rds("data/tours_msa.rds")
```


## Distribution of tour classification
Of individuals that make tours and filtered by MSA size (03) and individuals ages 18-65, below 
is the distribution of tour classification.

```{r distribution.tourclass, echo=F}
# histogram of tours
tours %>%
  ggplot(aes(x = tour_count, color = tour_class)) +
  geom_freqpoly()

tours %>% distributions(tour_class)

```


## Comparison of Tour Classification by Ability
Join with person characteristics





